name: publish_visualizer
on:
  push:
    tags:
      - "*"

env:
  GO_VERSION: "1.22"
  IMAGE_REPO: "ghcr.io/k0rdent/cluster-api-visualizer"

jobs:
  build:
    concurrency:
      group: build-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    name: Build and Unit Test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get outputs
        id: vars
        run: |
          GIT_VERSION=$(git describe --tags --always)
          echo "version=${GIT_VERSION}" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v6
        if: github.repository == 'k0rdent/cluster-api-visualizer'
        with:
          build-args: |
            LD_FLAGS=-s -w
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_REPO }}:${{ steps.vars.outputs.version }},${{ env.IMAGE_REPO }}:latest
          push: true
          no-cache: true
